version: '3'

services:
  database:
    container_name: mysql-ww
    ports:
      - "${DB_PORT_LOCAL}:${DB_PORT}"
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: $${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    cap_add:
      - SYS_NICE

  app:
    container_name: app-ww
    build:
      context: ./
    ports:
      - "${WEB_PORT_LOCAL}:${WEB_PORT}"
    image: mafio69/php72
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV}
      - DISPLAY_ERROR=${DISPLAY_ERROR}
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ./:/main
    links:
      - database:mysql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${WEB_PORT_LOCAL}" ]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mailtrap:
    container_name: mailtrap-ww
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1030:1025" # smtp server
      - "8035:8025" # web ui

  redis:
    image: bitnami/redis:6.2.6-debian-10-r117
    container_name: redis-tools
    ports:
      - "7004:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
