<?php

class TaskInstance extends \Eloquent {
    use \Illuminate\Database\Eloquent\SoftDeletingTrait;

    protected $fillable = ['task_id', 'user_id', 'task_step_id','date_collect', 'date_complete'];
    protected $dates = ['deleted_at', 'date_collect', 'date_complete'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new \Idea\Scopes\HasRelatedTask());
    }

    public function task()
    {
        return $this->belongsTo('Task');
    }

    public function user()
    {
        return $this->belongsTo('User');
    }

    public function step()
    {
        return $this->belongsTo('TaskStep', 'task_step_id');
    }

    public function history()
    {
        return $this->hasMany('TaskStepHistory');
    }

    public function latestHistory()
    {
        return $this->hasOne('TaskStepHistory')->orderBy('id', 'desc');
    }

    public function getOngoingAttribute()
    {
        return in_array( $this->task_step_id, [2]);
    }

    public function getCompletedAttribute()
    {
        return in_array( $this->task_step_id, [3,4,5]);
    }
}