<?php

class TaskGroup extends \Eloquent {
	protected $fillable = ['name', 'ord'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new \Idea\Scopes\OrderScope());
    }

	public function taskTypes()
    {
        return $this->hasMany('TaskType');
    }

    public function taskSubGroups()
    {
        return $this->hasMany('TaskSubgroup' , 'task_group_id');
    }

    public function users()
    {
        return $this->belongsToMany('User', 'user_task_group',  'task_group_id', 'user_id');
    }
}